name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-test:
    name: Format, Test, and Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the package and tooling needed for CI
          pip install .
          pip install pytest pytest-cov black

      - name: Black code style check
        run: |
          black --version
          black --check .

      - name: Run tests with coverage
        env:
          PYTHONPATH: src
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=src --cov-report=term --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          # If this is a private repo, set CODECOV_TOKEN in the repo secrets
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
